name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install SSH Key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@50.19.39.225 << 'EOF'
        cd /var/www/produ
        git pull origin main
        npm install
        npm run build
        sudo cp -r dist/* /var/www/html/
        sudo systemctl restart nginx
        EOF
